import type { Playbook } from "./types";

export const caio: Playbook = {
  id: "caio",
  label: "AI Leadership & Governance (CAIO)",
  sequence: [
    "AI ambition",
    "Business priorities",
    "Use-case portfolio",
    "AI readiness",
    "Governance",
    "Operating model",
    "Technology",
    "Data",
    "Talent",
    "Risk",
    "Roadmap",
    "Value tracking",
  ],
  coreQuestions: [
    "Where can AI create measurable value?",
    "What AI initiatives already exist?",
    "Who owns AI decisions?",
    "What data is available?",
    "What models and vendors are used?",
    "What controls exist?",
    "What skills exist?",
    "How should AI projects be funded and prioritized?",
  ],
  analysisStructure:
    "AI ambition → business priorities → use-case portfolio → readiness (data, technology, talent) → governance → operating model → risk → value tracking",
  solutionDimensions: [
    "build vs buy",
    "centralized vs federated AI teams",
    "governance",
    "model lifecycle",
    "responsible AI",
    "vendor strategy",
    "talent",
    "FinOps / AI costs",
    "adoption",
    "KPIs",
  ],
  optionTypology: [
    "Centralized AI center of excellence",
    "Hub & spoke (central platform + business domain teams)",
    "Decentralized in business units with light central governance",
  ],
  principles: [
    "The problem is not simply 'which AI tools should we buy?'.",
    "Target operating model: CAIO / AI leadership → AI governance → central AI platform/team → business domain teams → use-case delivery.",
    "Tie every AI investment to measurable value and a clear owner.",
  ],
  pilotPattern: "2-3 high-value use cases delivered through the target governance, with value tracked from day one",
  kpis: [
    "value delivered by AI use cases",
    "share of use cases in production vs POC",
    "time from idea to production",
    "AI run costs",
    "adoption",
    "incidents and compliance findings",
  ],
  relevantReflexes: ["E1", "E4", "E6", "E9"],
};
