import type { Playbook } from "./types";

export const dataPlatform: Playbook = {
  id: "data_platform",
  label: "Data Platform",
  sequence: [
    "Business use cases",
    "Data diagnosis",
    "Governance",
    "Target architecture",
    "Pilot",
    "Scale",
  ],
  coreQuestions: [
    "What business uses require the data?",
    "What data exists?",
    "Who produces it?",
    "Who owns it?",
    "Who consumes it?",
    "In which systems?",
    "What transformations already occur?",
    "What are the quality issues?",
    "What security or regulatory constraints exist?",
    "Should the data actually be centralized?",
  ],
  analysisStructure:
    "Source → Data → Format → Quality → Producer → Owner → Consumer → Usage → Transformation → Constraint",
  solutionDimensions: [
    "common definitions",
    "data governance",
    "data ownership",
    "data quality",
    "catalog",
    "lineage",
    "data contracts",
    "integration",
    "security",
    "permissions",
    "common platform",
    "federated platform",
    "hybrid architecture",
  ],
  optionTypology: [
    "Centralized platform (data physically consolidated)",
    "Federated platform (data stays in the entities, governed logical access)",
    "Hybrid (central for shareable data, federated for data that cannot leave)",
  ],
  principles: [
    "Never assume Data Platform = physical centralization.",
    "If some data cannot leave subsidiaries, consider a federated or hybrid architecture.",
    "Distinguish logical access / governance from physical data centralization.",
    "Avoid building '20% of the entire platform': build one complete vertical slice.",
  ],
  resolution: [
    "Identify business use cases",
    "Map datasets and stakeholders",
    "Harmonize business definitions",
    "Define governance",
    "Determine central / federated / hybrid target",
    "Define interfaces and data flows",
    "Pilot one valuable reporting use case",
    "Measure improvements",
    "Scale",
  ],
  pilotPattern: "2 subsidiaries → 1 dataset → 1 common definition → 1 pipeline → 1 dashboard → 1 measurable KPI",
  examples: [
    "Three subsidiaries with inconsistent KPIs, manual reporting and difficulty crossing datasets.",
  ],
  kpis: [
    "reporting production time",
    "share of KPIs with a common definition",
    "data quality score on the pilot dataset",
    "number of manual consolidation steps",
    "adoption of the common dashboard",
  ],
  relevantReflexes: ["E1", "E3", "E4", "E6", "E7", "E8"],
};
